{
 "title": "Master Replication",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Latency репликации 50q",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, operation) (\n    rate(btree_replication_e2e_latency_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency репликации 95q",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, operation) (\n    rate(btree_replication_e2e_latency_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency репликации 99q",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, operation) (\n    rate(btree_replication_e2e_latency_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heat map latency",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(btree_replication_e2e_latency_seconds_bucket[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lag на реплике 50q",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, instance, operation) (\n    rate(btree_replica_apply_lag_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lag на реплике 95q",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, instance, operation) (\n    rate(btree_replica_apply_lag_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lag на реплике 99q",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, instance, operation) (\n    rate(btree_replica_apply_lag_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lag локально на реплике 50q",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, instance, operation) (\n    rate(btree_replica_apply_latency_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lag локально на реплике 95q",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, instance, operation) (\n    rate(btree_replica_apply_latency_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lag локально на реплике 99q",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, instance, operation) (\n    rate(btree_replica_apply_latency_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heat map lag (replica 1)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(btree_replica_apply_lag_seconds_bucket{instance=\"host.docker.internal:8091\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heat map lag (replica 2)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(btree_replica_apply_lag_seconds_bucket{instance=\"host.docker.internal:8092\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Глубина очереди",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "btree_replication_outbox_queue_depth",
     "legendFormat": "__auto"
    },
    {
     "expr": "btree_replica_inbox_queue_depth",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inflight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    { "expr": "btree_replication_inflight", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Oldest inflight",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "btree_replication_oldest_inflight_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Send Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum by (replica, operation) (\n  rate(btree_replication_send_total{result=\"success\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Send Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "sum by (replica, operation) (\n  rate(btree_replication_send_total{result=\"failed\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ack Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum by (master, operation) (\n  rate(btree_replication_ack_total{result=\"success\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ack Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "sum by (master, operation) (\n  rate(btree_replication_ack_total{result=\"failed\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}